//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleBootsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public string Article { get; set; }
        public string ProductName { get; set; }
        public int UnitsID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int SupplierID { get; set; }
        public int ManufacturerID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Categoryes Categoryes { get; set; }
        public virtual Manufactures Manufactures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Units Units { get; set; }
    }
}
